### ISSUE TITLE
Sierra support

### ISSUE THREAD

**Issue by unnamed777** [nelsonjchen/fntoggle#4]
Unfortunately it doesn't work on Sierra. The app returns "res: 0" or "res: 1", but actual fn state isn't changed.

**Comment by nelsonjchen** [comment]
Hmm shoot. This is beyond my expertise. I'll try to take a look though.

**Comment by nelsonjchen** [comment]
I think this is a bit beyond me but I'll try to look this weekend. It looks like people doing this sort of thing are getting hit as evidenced by the Karabiner crew. Like anything that touches IOHIDKeyboard or something.

**Comment by unnamed777** [comment]
Thanks!
I thought I could replace some Karabiner mappings with hammerspoon + your application.

**Comment by nelsonjchen** [comment]
Odd, this works for me. I'm even using the binary I had uploaded to GitHub for `0.0.2`.

**Comment by nelsonjchen** [comment]
That said, what is your setup? It appears to work with the built-in keyboard of a Mid-2012 rMBP.

**Comment by unnamed777** [comment]
MBP mid 2014 15"

**Comment by nelsonjchen** [comment]
There might be one at work of similar or newer vintage. I'll check it out.

**Comment by unnamed777** [comment]
It turned out Karabiner-Elements interfers with your app even if its config doesn't have Fn mappings. When I quit Karabiner, the app works as it's supposed. Sorry for bothering you.

**Comment by nelsonjchen** [comment]
Not really bothering. Now that might be a TODO to put in the README. I myself am waiting for Elements to get non-Apple keyboard matching bindings to swap Command and WinKey and maybe I would have hit that soon.

**Comment by limeblack** [comment]
isn't this just an AppleScript.  I understand they updated AppleScript to be basically JavaScript but otherwise I think everything should still work fine shouldn't it?

**Comment by nelsonjchen** [comment]
This issue wasn't caused by an macOS update. It just couldn't coexist with Karabiner-Elements at that time. It still works fine on Sierra without Karabiner-Elements. 

We didn't test it, but I would guess that even the AppleScript approach wouldn't have worked with Karabiner-Elements at that time either. This tool toggles the underlying thing the stock checkbox would toggle. If the underlying thing is modified or bypassed due to things like Karabiner-Elements, AppleScript and/or whatever this is using wouldn't work anyway.

**Comment by nelsonjchen** [comment]
I haven't touched the active ingredients for that portion in this for the past 3 years. Still works.
