### ISSUE TITLE
command not found?

### ISSUE THREAD

**Issue by johnyradio** [nelsonjchen/fntoggle#5]
hi

- i placed in my Applications dir, 
- did `chmod +x fntoggle`, now it shows 'exec' icon
- at command-line, did `fntoggle on`. I noticed Tab key did not autocomplete the app name.
- getting 

> command not found

any suggestions?
thx

**Comment by nelsonjchen** [comment]
macOS usually does not have `/Applications/` in the PATH. If you put `fntoggle` into somewhere like `/usr/local/bin/`, it should just work.

**Comment by johnyradio** [comment]
hi, thx for reply. Tried copying to `usr/local/bin/`. Getting `permission denied`.

**Comment by nelsonjchen** [comment]
Oh, I guess I'm used to that being nearly world-writable due to Homebrew's default setup. I guess you could add `/Applications/` to your `$PATH`. Look up a guide for that.

Or, if you just want to get going and not read anything, use `/Applications/fntoggle` from the Terminal. In other words, that's just using the full path.

**Comment by johnyradio** [comment]
great! i prefer the full-path method. Not because i "don't want to read anything", but because i don't want to alter my system config to make an app work. Thx!

**Comment by nelsonjchen** [comment]
Ah, well, I think most people are willing to modify or _create_ their _user_ profile and add the paths. Something like prepending a `bin`directory under their home folder like `~/bin/` that they can freely drop executables into. You'll find many examples of that in people's "dotfiles" on Github that do just that. Or something else similar maybe. 

Anyway, glad to see that works for you!
